kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: fast
  namespace: stage
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4    
  zones: us-east-1a,us-east-1b,us-east-1c